// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddToLibrary(arg1:main.LibraryAnime):Promise<void>;

export function CloseWindow():Promise<void>;

export function CompleteMALAuth(arg1:string):Promise<void>;

export function DownloadEpisode(arg1:string,arg2:string):Promise<void>;

export function EnsureTools():Promise<void>;

export function ExportLibrary():Promise<string>;

export function GetAnimeDetails(arg1:string):Promise<main.Anime>;

export function GetAppVersion():Promise<string>;

export function GetDownloads():Promise<Array<string>>;

export function GetFinishedAiring():Promise<Array<main.TrendingAnime>>;

export function GetGenres():Promise<Array<string>>;

export function GetLibrary():Promise<Array<main.LibraryAnime>>;

export function GetLibraryItem(arg1:string):Promise<main.LibraryAnime>;

export function GetMALAuthURL():Promise<string>;

export function GetMALStatus():Promise<string>;

export function GetNewFinishedAiring():Promise<Array<main.TrendingAnime>>;

export function GetNotificationsEnabled():Promise<string>;

export function GetPlatform():Promise<string>;

export function GetRecentEpisodes():Promise<Array<main.TrendingAnime>>;

export function GetSchedule():Promise<Array<main.SearchResult>>;

export function GetSetting(arg1:string):Promise<string>;

export function GetStreamURL(arg1:string,arg2:string):Promise<Array<main.StreamSource>>;

export function GetTopAnime(arg1:string):Promise<Array<main.SearchResult>>;

export function GetTrending():Promise<Array<main.TrendingAnime>>;

export function GetUpcoming():Promise<Array<main.TrendingAnime>>;

export function ImportLibrary(arg1:string):Promise<number>;

export function ImportLibraryFromFile():Promise<number>;

export function InitPlayer(arg1:string):Promise<void>;

export function MPVStop():Promise<void>;

export function MaximizeWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function OpenFile():Promise<string>;

export function OpenFolder():Promise<string>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function PlayInMPV(arg1:string):Promise<void>;

export function RemoveFromLibrary(arg1:string):Promise<void>;

export function SaveLibraryToFile():Promise<void>;

export function SearchAnime(arg1:string,arg2:number):Promise<Array<main.SearchResult>>;

export function SetNotificationsEnabled(arg1:boolean):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SyncToMAL():Promise<void>;

export function UpdateLibraryItem(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;
