// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToLibrary(arg1) {
  return window['go']['main']['App']['AddToLibrary'](arg1);
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function CompleteMALAuth(arg1) {
  return window['go']['main']['App']['CompleteMALAuth'](arg1);
}

export function DownloadEpisode(arg1, arg2) {
  return window['go']['main']['App']['DownloadEpisode'](arg1, arg2);
}

export function EnsureTools() {
  return window['go']['main']['App']['EnsureTools']();
}

export function ExportLibrary() {
  return window['go']['main']['App']['ExportLibrary']();
}

export function GetAnimeDetails(arg1) {
  return window['go']['main']['App']['GetAnimeDetails'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetDownloads() {
  return window['go']['main']['App']['GetDownloads']();
}

export function GetFinishedAiring() {
  return window['go']['main']['App']['GetFinishedAiring']();
}

export function GetGenres() {
  return window['go']['main']['App']['GetGenres']();
}

export function GetLibrary() {
  return window['go']['main']['App']['GetLibrary']();
}

export function GetLibraryItem(arg1) {
  return window['go']['main']['App']['GetLibraryItem'](arg1);
}

export function GetMALAuthURL() {
  return window['go']['main']['App']['GetMALAuthURL']();
}

export function GetMALStatus() {
  return window['go']['main']['App']['GetMALStatus']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetRecentEpisodes() {
  return window['go']['main']['App']['GetRecentEpisodes']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetStreamURL(arg1, arg2) {
  return window['go']['main']['App']['GetStreamURL'](arg1, arg2);
}

export function GetTrending() {
  return window['go']['main']['App']['GetTrending']();
}

export function GetUpcoming() {
  return window['go']['main']['App']['GetUpcoming']();
}

export function ImportLibrary(arg1) {
  return window['go']['main']['App']['ImportLibrary'](arg1);
}

export function ImportLibraryFromFile() {
  return window['go']['main']['App']['ImportLibraryFromFile']();
}

export function InitPlayer(arg1) {
  return window['go']['main']['App']['InitPlayer'](arg1);
}

export function MPVStop() {
  return window['go']['main']['App']['MPVStop']();
}

export function MaximizeWindow() {
  return window['go']['main']['App']['MaximizeWindow']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function PlayInMPV(arg1) {
  return window['go']['main']['App']['PlayInMPV'](arg1);
}

export function RemoveFromLibrary(arg1) {
  return window['go']['main']['App']['RemoveFromLibrary'](arg1);
}

export function SaveLibraryToFile() {
  return window['go']['main']['App']['SaveLibraryToFile']();
}

export function SearchAnime(arg1) {
  return window['go']['main']['App']['SearchAnime'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SyncToMAL() {
  return window['go']['main']['App']['SyncToMAL']();
}

export function UpdateLibraryItem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateLibraryItem'](arg1, arg2, arg3, arg4);
}
